### ISSUE TITLE
How to set/get a cover image?

### ISSUE THREAD

**Issue by LukasKnuth** [mikkyang/id3-go#11]
I have played around with the library and since there's no default way (at least I didn't see one) of setting a cover-image for an MP3 file, I put this into the `frame.go`-file (since it uses internal variables of `ImageFrame`):

```
func NewImageFrame(ft FrameType, mime_type string, image_data []byte) *ImageFrame{
	data_frame := NewDataFrame(ft, image_data)
	data_frame.size += 1 // Add space for the pictureType (do we need this??)
	image_frame := &ImageFrame{
		DataFrame: *data_frame, // DataFrame header
		pictureType: byte(0x03), // Image Type, in this case Front Cover (http://id3.org/id3v2.3.0#Attached_picture)
	}
	image_frame.SetEncoding("UTF-8")
	image_frame.SetMIMEType(mime_type)
	return image_frame
}
```

However, this does not work. Am I missing something or is there an easier way?

Also, when I use this `image_frame := mp3.Tagger.Frame("APIC")` to see if the file already has a cover-art (which it does), it returns `nil`.

**Comment by mro** [comment]
@mikkyang any chance to get `NewImageFrame` added to master branch?

**Comment by bogem** [comment]
I wrote a solution: https://github.com/bogem/id3v2
