### ISSUE TITLE
Bitrate?

### ISSUE THREAD

**Issue by dopgm** [mikkyang/id3-go#20]
Hi,

Please advise how to pull bitrate value?

Also, is "id3-go" choosing ID3 version automatically if I import just "github.com/mikkyang/id3-go"?

Thank you!

**Comment by mikkyang** [comment]
As far as I know, ID3 doesn't have a bitrate field. This is part of the encoding standard (MP3, etc.) rather than in the ID3 tag.

I found this if it helps: [http://id3.org/mp3Frame](http://id3.org/mp3Frame)
