### ISSUE TITLE
Can not set tags with UTF-8 contents

### ISSUE THREAD

**Issue by formalin14** [mikkyang/id3-go#22]
func tagIt(filename string, title string, album string, artist string, genre string) {
    mp3File, err := id3.Open(filename)
    if err != nil {
        panic(err)
    }
    defer mp3File.Close()
    mp3File.SetArtist(artist + "x")
    mp3File.SetAlbum("哈哈")
    mp3File.SetTitle(title + "x")
    mp3File.SetGenre(genre + "x")
}

pure English works, but Chinese not.

Should I convert the Chinese string to some other encoding first?

**Comment by mikkyang** [comment]
Did you try setting the encoding on the frame? With `SetEncoding("UTF-8")` or something like that.

**Comment by formalin14** [comment]
I did much trick to make v2 work, but v1 does not work(got mess code). Below is my code now:

func setFrame(tag *id3.File, frameName string, value string) bool {
    frame := tag.Frame(frameName)
    if frame != nil {
	fmt.Println("changing frame")
        if textFramer, ok := frame.(v2.TextFramer); ok {
            textFramer.SetEncoding("UTF-8")
            textFramer.SetText(value)
            return true
        }
    } else {
        fmt.Println("adding frame")
        ft := v2.V23FrameTypeMap[frameName]
        textFrame := v2.NewTextFrame(ft, "")
        textFrame.SetEncoding("UTF-8")
        textFrame.SetText(value)
	tag.AddFrames(textFrame)
    }
    return false
}


if mp3File.Version() == "1.0" {
        mp3File.SetTitle(title)
        mp3File.SetAlbum(album)
        mp3File.SetArtist(artist)
    } else {
        setFrame(mp3File, "TIT2", title)
        setFrame(mp3File, "TALB", album)
        setFrame(mp3File, "TPE1", artist)
    }
    mp3File.SetGenre("Hip-Hop")

because v1 does not contain frames, so I use SetTitle() directly, but got mess code.

**Comment by mikkyang** [comment]
v1 does not support Unicode
